# Databricks notebook source
# MAGIC %md
# MAGIC # ABAC in Databricks Unity Catalog: A Step-by-Step Guide to Row Filters and Column Masks
# MAGIC
# MAGIC **Article:** [ABAC in Databricks Unity Catalog: A Step-by-Step Guide to Row Filters and Column Masks](https://medium.com/@cralle/a-step-by-step-guide-to-setting-up-abac-in-databricks-unity-catalog-8266454bc87f?sk=f6ae1e1a285d4bd2b04a8ebf1225cc8d)
# MAGIC
# MAGIC A hands-on, step-by-step walkthrough for setting up Attribute-Based Access Control (ABAC)
# MAGIC in Databricks Unity Catalog: governed tags, the UDFs that back a row filter and a column
# MAGIC mask, the ABAC policies that tie them together, and how to verify the result.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Overview
# MAGIC
# MAGIC Attribute-Based Access Control (ABAC) in Databricks Unity Catalog went generally
# MAGIC available on April 28, 2026. Instead of writing an access control list per table, ABAC
# MAGIC lets you define a policy once, for example "hide EU customer rows", and have it apply
# MAGIC automatically to every object that carries the matching tag.
# MAGIC
# MAGIC ABAC complements, rather than replaces, Unity Catalog's privilege model. You still grant
# MAGIC privileges like `SELECT`; ABAC layers conditional, tag-driven access on top of that.
# MAGIC Row filter and column mask policies apply to tables, materialized views, and streaming
# MAGIC tables. There is also a separate GRANT policy type (Beta) for dynamic `EXECUTE` grants on
# MAGIC models, which this notebook does not cover.
# MAGIC
# MAGIC ABAC relies on three components:
# MAGIC
# MAGIC 1. **Governed tags** - account-level tag keys, for example `pii:ssn` or `geo_region:region`.
# MAGIC 2. **Policies** - a row filter (hides rows) or a column mask (masks column values),
# MAGIC    applied at the catalog, schema, or table level. A policy on a catalog or schema
# MAGIC    cascades down to every table underneath it. Tag inheritance has one exception: tags
# MAGIC    inherited from a catalog or schema apply during policy evaluation everywhere except at
# MAGIC    the column level.
# MAGIC 3. **User-defined functions (UDFs)** - the policy calls a UDF to decide whether to hide a
# MAGIC    row or what value to substitute for a masked column.
# MAGIC
# MAGIC At GA, policies can be created three ways: the Catalog Explorer UI, the `CREATE POLICY`
# MAGIC SQL statement (Databricks Runtime 16.4+ or serverless), or the REST API, SDK, or
# MAGIC Terraform. This notebook shows both the UI path (as reference, since it cannot be
# MAGIC scripted) and the SQL path (fully runnable) for each policy.
# MAGIC
# MAGIC Use ABAC when you manage large catalogs, need dynamic per-region or per-persona rules, or
# MAGIC must enforce compliance rules such as GDPR, PCI, or HIPAA at scale. Avoid it, for now,
# MAGIC when:
# MAGIC
# MAGIC - You need to attach a policy directly to a **view**. Policies still cannot be attached to
# MAGIC   a view, but policies on the underlying tables are enforced when you query through the
# MAGIC   view, evaluated using the session user's identity.
# MAGIC - You expect multiple row filters or column masks to combine automatically on the same
# MAGIC   object. Only one distinct row filter can resolve per user per table, and only one
# MAGIC   distinct column mask can resolve per user per column, so combine logic with `AND` inside
# MAGIC   a single UDF instead of stacking policies.
# MAGIC - Your compute is older than **DBR 16.4** and isn't serverless. Standard or dedicated
# MAGIC   compute on older runtimes can't read ABAC-secured tables.
# MAGIC
# MAGIC This notebook:
# MAGIC
# MAGIC 1. Creates a small CH Enterprise `clients` table with US and EU records (**Setup**).
# MAGIC 2. Walks through creating the governed tags that this tutorial depends on
# MAGIC    (**Manual setup required**).
# MAGIC 3. Tags the sensitive columns.
# MAGIC 4. Creates a UDF and a row filter policy that hides EU customer rows.
# MAGIC 5. Creates a UDF and a column mask policy that redacts SSNs.
# MAGIC 6. Verifies the enforced behavior.
# MAGIC 7. Removes the policies, functions, and sample table (**Cleanup**).

# COMMAND ----------

# MAGIC %md
# MAGIC ## Setup
# MAGIC
# MAGIC Create the CH Enterprise `clients` table in the `testing.default` catalog and
# MAGIC schema: eight sample client records, four in the US and four in the EU, each with an
# MAGIC address, a Social Security Number (SSN), and a region. `id` is declared as an identity
# MAGIC column so it does not need to be supplied when writing rows.

# COMMAND ----------

catalog = "testing"
schema = "default"
table = f"{catalog}.{schema}.clients"

spark.sql(f"CREATE CATALOG IF NOT EXISTS {catalog}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{schema}")

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {table} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  address STRING,
  ssn STRING,
  region STRING
)
USING DELTA
""")

data = [
    ("123 Main St, NY, US", "123-45-6789", "US"),
    ("456 Oak St, CA, US", "234-56-7890", "US"),
    ("12 Abbey Street, Dublin, Ireland", "111-22-3333", "EU"),
    ("45 Rue de Rivoli, Paris, France", "222-33-4444", "EU"),
    ("789 Pine St, TX, US", "345-67-8901", "US"),
    ("23 Via Roma, Milan, Italy", "444-55-6666", "EU"),
    ("321 Maple St, FL, US", "456-78-9012", "US"),
    ("78 Berliner Str., Berlin, Germany", "333-44-5555", "EU"),
]

df = spark.createDataFrame(data, ["address", "ssn", "region"])
df.write.mode("append").saveAsTable(table)

display(spark.table(table))

# COMMAND ----------

# MAGIC %md
# MAGIC Before any ABAC policy exists, every column and every row is fully visible to any reader
# MAGIC with `SELECT` on the table. Confirm the US/EU split now, so the row filter's effect later
# MAGIC is easy to check.

# COMMAND ----------

import pyspark.sql.functions as F

region_counts = (
    spark.table(table)
    .groupBy(F.col("region"))
    .agg(F.count("*").alias("num_clients"))
    .orderBy(F.col("region"))
)
display(region_counts)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Manual setup required
# MAGIC
# MAGIC Governed tags are account-level objects: the tag key itself, its allowed values, and who
# MAGIC is permitted to apply it are defined once per account, not per workspace, and there is no
# MAGIC SQL or PySpark statement that creates one. Complete this before running the tagging cell
# MAGIC below if you want it enforced as a governed tag rather than an ordinary one; the
# MAGIC `ALTER ... SET TAGS` statements later in this notebook will still run without it, they
# MAGIC just apply as plain, ungoverned tags until the policy exists.
# MAGIC
# MAGIC ### 1. Create the governed tags
# MAGIC
# MAGIC This tutorial uses two tag keys: `pii` (values `ssn` and `address`) and `geo_region`
# MAGIC (value `region`). For each one:
# MAGIC
# MAGIC 1. In the workspace sidebar, open **Data**, then **Governance**, then **Governed Tags**
# MAGIC    (account admins can also reach this from the account console under **Governance**).
# MAGIC 2. Click **Create governed tag**.
# MAGIC 3. Enter the tag key exactly as used in this notebook, `pii` or `geo_region`. Tag keys are
# MAGIC    case sensitive.
# MAGIC 4. Add the allowed values for that key: `ssn` and `address` for `pii`; `region` for
# MAGIC    `geo_region`. You can also leave a key unrestricted if you don't want to enforce a
# MAGIC    fixed value list.
# MAGIC 5. Set who is permitted to create, manage, and assign the tag, either account-wide or per
# MAGIC    tag, from the same screen.
# MAGIC 6. Click **Create**, and repeat for the second tag key.
# MAGIC
# MAGIC Allow up to roughly 30 seconds (occasionally longer) for the tag and its permissions to
# MAGIC propagate before you rely on it elsewhere.
# MAGIC
# MAGIC ### 2. Everything after this is scriptable
# MAGIC
# MAGIC Once the `pii` and `geo_region` governed tags exist, tagging the columns, creating the
# MAGIC row filter and column mask UDFs, and creating the ABAC policies themselves are all
# MAGIC expressible in SQL (via `CREATE POLICY`, GA on DBR 16.4+ or serverless) and run directly
# MAGIC in the cells below, no account console step required for any of it.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Tag the sensitive columns
# MAGIC
# MAGIC Apply the `pii` tag to the `ssn` and `address` columns, and the `geo_region` tag to the
# MAGIC `region` column. This is ordinary `ALTER TABLE ... ALTER COLUMN ... SET TAGS` syntax,
# MAGIC whether or not the tag key has been governed in the account console.

# COMMAND ----------

# MAGIC %sql
# MAGIC ALTER TABLE testing.default.clients
# MAGIC ALTER COLUMN ssn
# MAGIC SET TAGS ('pii' = 'ssn');
# MAGIC
# MAGIC ALTER TABLE testing.default.clients
# MAGIC ALTER COLUMN address
# MAGIC SET TAGS ('pii' = 'address');
# MAGIC
# MAGIC ALTER TABLE testing.default.clients
# MAGIC ALTER COLUMN region
# MAGIC SET TAGS ('geo_region' = 'region');

# COMMAND ----------

# MAGIC %md
# MAGIC ## Row filter: hide EU customer rows
# MAGIC
# MAGIC First, a UDF that returns `TRUE` for a non-EU region and `FALSE` for `EU`. Filtering on a
# MAGIC dedicated, tagged region column like this is more reliable than a substring match against
# MAGIC a free-text address field.

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE FUNCTION testing.default.non_eu_region(region STRING)
# MAGIC RETURNS BOOLEAN
# MAGIC RETURN region <> 'EU';

# COMMAND ----------

# MAGIC %md
# MAGIC This function returns `FALSE` for EU-tagged rows, so the row filter policy hides them.
# MAGIC
# MAGIC In **Catalog Explorer**, the equivalent policy is created like this (shown for reference;
# MAGIC this UI path cannot be scripted from a notebook):
# MAGIC
# MAGIC - Navigate to **testing -> Policies -> New policy**
# MAGIC - Name: **hide_eu_customers**
# MAGIC - Applied to: **All account users**
# MAGIC - Scope: **Catalog = testing, schema = default, All tables**
# MAGIC - Purpose: **Hide table rows**
# MAGIC - Conditions: Use existing function -> select `non_eu_region`
# MAGIC - Function parameters: Map tag `geo_region:region` to the function parameter
# MAGIC - Save the policy
# MAGIC
# MAGIC At GA you can also create the same policy directly in SQL, which is what the cell below
# MAGIC runs:

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE POLICY hide_eu_customers
# MAGIC ON SCHEMA testing.default
# MAGIC COMMENT 'Hide EU customer rows from US analysts'
# MAGIC ROW FILTER testing.default.non_eu_region
# MAGIC TO `account users`
# MAGIC FOR TABLES
# MAGIC MATCH COLUMNS has_tag('geo_region') AS region
# MAGIC USING COLUMNS (region);

# COMMAND ----------

# MAGIC %md
# MAGIC Now every table in `testing.default` with a column tagged `geo_region` will have its
# MAGIC EU rows filtered for anyone matched by the policy's `TO` clause.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM testing.default.clients;
# MAGIC -- Returns only non-EU customer rows

# COMMAND ----------

# MAGIC %md
# MAGIC ## Column mask: redact SSNs
# MAGIC
# MAGIC Next, a UDF that always returns a fixed, masked string in place of the real SSN value.

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REPLACE FUNCTION testing.default.mask_ssn(ssn STRING)
# MAGIC RETURNS STRING
# MAGIC RETURN '***-**-****';

# COMMAND ----------

# MAGIC %md
# MAGIC In **Catalog Explorer**, the equivalent policy is created like this (shown for reference;
# MAGIC this UI path cannot be scripted from a notebook):
# MAGIC
# MAGIC - Go to **Policies -> New policy**
# MAGIC - Name: **mask_ssn**
# MAGIC - Applied to: **All account users**
# MAGIC - Scope: **Catalog = testing, schema = default, All tables**
# MAGIC - Purpose: **Mask column data**
# MAGIC - Condition: Mask column if tagged with `pii:ssn`
# MAGIC - Function: Select existing = `mask_ssn`
# MAGIC - Save the policy
# MAGIC
# MAGIC At GA you can also create the same policy directly in SQL, which is what the cell below
# MAGIC runs:

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE POLICY mask_ssn
# MAGIC ON SCHEMA testing.default
# MAGIC COLUMN MASK testing.default.mask_ssn
# MAGIC TO `account users`
# MAGIC FOR TABLES
# MAGIC MATCH COLUMNS has_tag_value('pii', 'ssn') AS ssn
# MAGIC ON COLUMN ssn;

# COMMAND ----------

# MAGIC %md
# MAGIC ## Verify
# MAGIC
# MAGIC With both policies in place, querying the table now returns only non-EU rows, and the
# MAGIC `ssn` column is replaced with the masked value for anyone matched by the policies' `TO`
# MAGIC clause. If you run this notebook as a catalog owner or metastore admin, enforcement may
# MAGIC look different than for an ordinary account user; test with a non-privileged user or
# MAGIC group if you need to confirm end-user behavior exactly.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM testing.default.clients;
# MAGIC -- Non-EU rows only, with SSNs replaced by ***-**-****

# COMMAND ----------

# MAGIC %md
# MAGIC The same check from PySpark, counting what remains visible after both policies apply:

# COMMAND ----------

visible = spark.table(table)
display(
    visible
    .select(F.col("id"), F.col("region"), F.col("ssn"))
    .orderBy(F.col("id"))
)
print(f"Visible rows after the row filter: {visible.count()}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Cleanup
# MAGIC
# MAGIC Drop the two policies, the two UDFs, and the sample table. This does not remove the
# MAGIC `pii` and `geo_region` governed tag definitions created manually in the account console;
# MAGIC delete those there directly (**Governed Tags** -> select the tag -> **Delete**) if you no
# MAGIC longer want them.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- DROP POLICY does not support IF EXISTS; run this only after the policies above were created.
# MAGIC DROP POLICY hide_eu_customers ON SCHEMA testing.default;
# MAGIC DROP POLICY mask_ssn ON SCHEMA testing.default;
# MAGIC
# MAGIC DROP FUNCTION IF EXISTS testing.default.non_eu_region;
# MAGIC DROP FUNCTION IF EXISTS testing.default.mask_ssn;
# MAGIC
# MAGIC DROP TABLE IF EXISTS testing.default.clients;

# COMMAND ----------

print("Policies, functions, and the sample clients table have been dropped.")

# COMMAND ----------

# MAGIC %md
# MAGIC **Notes:** ABAC in Unity Catalog went generally available on April 28, 2026, and requires
# MAGIC Databricks Runtime 16.4 or above, or serverless compute, to read ABAC-secured tables.
# MAGIC Creating the `pii` and `geo_region` governed tags themselves is treated here as an account
# MAGIC console or Catalog Explorer UI step; see "Manual setup required" above. Everything else in
# MAGIC this notebook, tagging columns, defining the UDFs, creating the `CREATE POLICY` statements,
# MAGIC and verifying the result, runs as ordinary SQL and PySpark against the `testing.default`
# MAGIC sandbox catalog and schema.
